config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :players do
    collection do
      get 'rank'
      get 'active'
    end
  end

  root 'players#rank'

end

app/models/player.rb
class Player < ActiveRecord::Base
  CURRENT_YEAR = 2014

  attr_accessor :rank
  attr_accessor :tie

  def short_name
    splits = name.split(' ')
    "#{splits[0]} #{splits[-1][0]}"
  end

  def self.active
    Player.for_year(CURRENT_YEAR)
  end

  def self.for_year(year)
    Player.
      joins("inner join teams on teams.manager_id = players.id or teams.assistant_id = players.id").
      where('teams.year = ?', year).
      distinct
  end

  def is_active?
    teams.where('teams.year = ?', CURRENT_YEAR).size > 0
  end
  
  def teams
      @teams ||= Team.where("manager_id = ? or assistant_id = ?", id, id)
  end

  def image_path
    #FIXME rename image url
    "avatars/#{image_url}".split('.')[0]
  end

  def avg_wins
    total_wins/total_years.to_f
  end

  def avg_draft
    teams.sum(:draft)/total_years.to_f
  end

  def total_earnings
    teams.inject(0) do |sum, team|
      sum += team.assistant ? team.earnings/2 : team.earnings
    end
  end

  def avg_earnings
    total_earnings / total_years
  end

  def total_lowseed
    teams.lowseed.size
  end

  def total_pts_champ
    teams.ptschamp.size
  end

  def total_champ
    teams.champ.size
  end

  def total_years
    teams.size
  end

  def total_wins
    teams.sum(:wins)
  end

  def total_goat
    teams.goat.size
  end

  def total_badges_for(type)
    case type
      when :total_lowseed then total_lowseed
      when :total_pts_champ then total_pts_champ
      when :total_champ then total_champ
      when :total_goat then total_goat
      else 0
    end
  end

  def next
    players = Player.all.to_a
    players[(players.index(self) + 1) % players.size]
  end

  def prev
    players = Player.all.to_a
    players[players.index(self) - 1]
  end

  def rank_for(sort, filter="all")
    return nil if filter == "active" and !is_active?
    rankings = Leaderboard.new({filter:filter, sort:sort}).rankings
    #rankings = Leaderboard.new({filter:"all", sort:"goat"}).rankings
    puts "#{rankings.map{|u| [u.rank, u.name]}}"
    puts "#{rankings.index(self)}"
    ranked_player = rankings[rankings.index(self)]
    ranked_player.tie ? "T#{ranked_player.rank}" : "#{ranked_player.rank}"
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  helper_method :filter, :sort

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  def rank
    @players = Leaderboard.new(params).rankings
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Helpers
  # TODO current_filter, current_sort
  def filter
    params[:filter] ? params[:filter] : "active"
  end

  def sort
    params[:sort] ? params[:sort] : "avg_earnings"
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :years, :wins, :draft, :champ, :pts_champ, :low_seed, :goat, :total, :image_url, :active, :wins_avg, :draft_avg, :total_avg)
    end

end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :years %><br>
    <%= f.number_field :years %>
  </div>
  <div class="field">
    <%= f.label :wins %><br>
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :draft %><br>
    <%= f.number_field :draft %>
  </div>
  <div class="field">
    <%= f.label :champ %><br>
    <%= f.number_field :champ %>
  </div>
  <div class="field">
    <%= f.label :pts_champ %><br>
    <%= f.number_field :pts_champ %>
  </div>
  <div class="field">
    <%= f.label :low_seed %><br>
    <%= f.number_field :low_seed %>
  </div>
  <div class="field">
    <%= f.label :goat %><br>
    <%= f.number_field :goat %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :wins_avg %><br>
    <%= f.text_field :wins_avg %>
  </div>
  <div class="field">
    <%= f.label :draft_avg %><br>
    <%= f.text_field :draft_avg %>
  </div>
  <div class="field">
    <%= f.label :total_avg %><br>
    <%= f.text_field :total_avg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<tr id="<%=player.id%>" data-player="<%= player.id %>">
  <td class="half"><h1><%= player.rank %><sup><%= player.tie ? "*" : "".html_safe %></sup></h1></td>
  <td><%= image_tag player.image_path,  class:"pic" %></td>
  <td class="stats">
    <a href="<%= player_path(player) %>"><%= player.short_name%> </a>
    <br>
      &nbsp;Years Played: <%= player.total_years %> <br>
      &nbsp;Wins (avg): <%= number_with_precision(player.avg_wins, precision:1) %> <br>
      &nbsp;Draft (avg): <%= number_with_precision(player.avg_draft, precision:1) %>
  </td>
  <td class="badges badgecell">
    <ul>
    <% Badge.ordered(sort).each do |badge| %>
      <%if player.total_badges_for(badge.type) > 0 %>
        <li> <%= image_tag(badge.image_url, class:"badge") %> X <%=player.total_badges_for(badge.type)%></li>
      <% end %>
    <% end %>
  </td>
  <td class="half"><h2><%= number_to_currency(player.total_earnings, precision:0) %></h2></td>
  <td class="half"><h2><%= number_to_currency(player.avg_earnings, precision:0) %></h2></td>
</tr>

app/views/players/_teams.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Year</th>
      <th>Name</th>
      <th>Manager</th>
      <th>Assistant</th>
      <th>Draft</th>
      <th>R1</th>
      <th>R2</th>
      <th>R3</th>
      <th>R4</th>
      <th>R5</th>
      <th>R6</th>
      <th>Wins</th>
      <th>Pts</th>
      <th>Earnings</th>
      <th>Ptschamp</th>
      <th>Champ</th>
      <th>Low</th>
      <th>Goat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player.teams.each do |team| %>
      <tr>
        <td><%= team.id %></td>
        <td><%= team.year %></td>
        <td><%= team.name %></td>
        <td><%= team.manager.name %></td>
        <td><%= team.assistant.name if team.assistant %></td>
        <td><%= team.draft %></td>
        <td><%= team.r1 %></td>
        <td><%= team.r2 %></td>
        <td><%= team.r3 %></td>
        <td><%= team.r4 %></td>
        <td><%= team.r5 %></td>
        <td><%= team.r6 %></td>
        <td><%= team.wins %></td>
        <td><%= team.pts %></td>
        <td><%= team.earnings %></td>
        <td><%= team.ptschamp ? "X":"" %></td>
        <td><%= team.r6 == 1 ? "X":"" %></td>
        <td><%= team.low ? "X":""%></td>
        <td><%= team.goat ? "X":"" %></td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Years</th>
      <th>Wins</th>
      <th>Draft</th>
      <th>Champ</th>
      <th>Pts champ</th>
      <th>Low seed</th>
      <th>Goat</th>
      <th>Total</th>
      <th>Image url</th>
      <th>Active</th>
      <th>Wins avg</th>
      <th>Draft avg</th>
      <th>Total avg</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.short_name %></td>
        <td><%= player.years %></td>
        <td><%= player.wins %></td>
        <td><%= player.draft %></td>
        <td><%= player.champ %></td>
        <td><%= player.pts_champ %></td>
        <td><%= player.low_seed %></td>
        <td><%= player.goat %></td>
        <td><%= player.total %></td>
        <td><%= player.image_url %></td>
        <td><%= player.active %></td>
        <td><%= player.wins_avg %></td>
        <td><%= player.draft_avg %></td>
        <td><%= player.total_avg %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/rank.html.erb
<% content_for :page_title do %>
  <h1>Leaderboard</h1>

  <div class="subtitle">
    <% if badge=Badge.for_sort(sort) %>
      <%= image_tag(badge.image_url, class:"badge") %>
    <% end %>
    <%= rank_subtitle %>
  </div>

  <div class="table-options">

    <% ordered_rank_sort_keys.each do |key| %>
      <% selected = key == sort.to_sym ? "selected" : "" %>
      <%= link_to(rank_sort_options[key], rank_players_path(sort:key, filter:filter), class:selected) %>
    <% end %>

    &nbsp;|&nbsp;
      <% rank_filter_options.each do |option, text| %>
        <% selected = option == filter.to_sym ? "selected" : "" %>
        <%= link_to(text, rank_players_path(sort:sort, filter:option), class:selected) %>
      <% end %>
  </div>
<% end %>


<table>
  <% 6.times do %> <col> <% end %>
  <thead>
    <tr>
      <th>Rank</th>
      <th></th>
      <th></th>
      <th>Badges</th>
      <th>Total</th>
      <th>Avg</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <%= render 'player', player:player %>
    <% end %>
  </tbody>
</table>

app/views/players/show.html.erb
<% content_for :nav do %>
  <%= link_to "Leaderboard", rank_players_path %> |
  <%= link_to "Prev", player_path(@player.prev) %> |
  <%= link_to "Next", player_path(@player.next) %>
<% end %>


<% content_for :page_title do %>
  
  <div style="position:relative; width:100%">
    <%= image_tag @player.image_path, class:"avatar" %>
    <h1 style="font-size:18px;position:absolute; bottom:25px; right:0;left:0;margin:0 auto"><%= @player.short_name %></h1>
    
  </div>
  <div style="clear: both;"></div>

<% end %>

  <div id="summary">
    <table id="player-summary">
      <% 5.times do %> <col> <% end %>
      <thead>
        <tr>
          <th width="100">Stat<br>&nbsp;</td>
          <th width="50"></td>
          <th width="50">Rank <br><span style="font-size:8px;color:gray">All Time</td>
          <th width="50">Rank <br><span style="font-size:8px;color:gray">Current</td>
          <th >Years <br>&nbsp;</td>
        </tr>
      </thead
      <tbody>

      <tr>
        <td>Avg Winning: </td>
        <td><%= number_to_currency(@player.avg_earnings) %></td>
        <td><%= rank_all_link_to(@player, "avg_earnings") %></td>
        <td><%= rank_active_link_to(@player, "avg_earnings") %></td>
        <td></td></tr>

      <tr>
        <td>Total Winnings: </td>
        <td><%= number_to_currency(@player.total_earnings) %> </td>
        <td><%= rank_all_link_to(@player, "total_earnings") %></td>
        <td><%= rank_active_link_to(@player, "total_earnings") %></td>
        <td></td></tr>

      <tr>
        <td width="100">Years Played: </td>
        <td width="50"><%= pluralize(@player.total_years, "year") %></td>
        <td><%= rank_all_link_to(@player, "total_years") %></td>
        <td><%= rank_active_link_to(@player, "total_years") %></td>
        <td></td></tr>

      <tr>
        <td>Avg Wins Per Year: </td>
        <td><%= number_with_precision(@player.avg_wins, precision:1) %></td>
        <td><%= rank_all_link_to(@player, "avg_wins") %></td>
        <td><%= rank_active_link_to(@player, "avg_wins") %></td>
        <td></td></tr>

      <tr>
        <td>Avg Draft Position: </td>
        <td class="valuecell"><%= number_with_precision(@player.avg_draft, precision:1) %></td>
        <td><%= rank_all_link_to(@player, "avg_draft") %></td>
        <td><%= rank_active_link_to(@player, "avg_draft") %></td>
        <td></td></tr>

      <tr>
         <td><%= image_tag("ptscrown_sm.png", width:"10px") %> Points Winner:</td>
         <td><%= @player.total_pts_champ > 0? pluralize(@player.total_pts_champ, "year") : "" %></td>
         <td><%= rank_all_link_to(@player, "total_pts_champ") %></td>
         <td><%= rank_active_link_to(@player, "total_pts_champ") %></td>
         <td><%= @player.teams.ptschamp.years.join(",") %></td></tr>

      <tr>
        <td><%= image_tag("crown_sm.png", width:"10px") %> Picked Winner:</td>
        <td><%= @player.total_champ > 0? pluralize(@player.total_champ, "year") : "" %></td>
        <td><%= rank_all_link_to(@player, "total_champ") %></td>
        <td><%= rank_active_link_to(@player, "total_champ") %></td>
        <td><%= @player.teams.champ.years.join(",") %></td></tr>

      <tr>
        <td><%= image_tag("acorn_sm.png", width:"10px") %> Low Seed Winner:</td>
        <td><%= @player.total_lowseed > 0? pluralize(@player.total_lowseed, "year") : "" %></td>
        <td><%= rank_all_link_to(@player, "total_lowseed") %></td>
        <td><%= rank_active_link_to(@player, "total_lowseed") %></td>
        <td><%= @player.teams.lowseed.years.join(",") %></td></tr>

      <tr>
        <td><%= image_tag("goat_sm.png", width:"10px") %> Fewest Points:</td>
        <td><%= @player.total_goat > 0? pluralize(@player.total_goat, "year") : "" %></td>
        <td><%= rank_all_link_to(@player, "total_goat") %></td>
        <td><%= rank_active_link_to(@player, "total_goat") %></td>
        <td><%= @player.teams.goat.years.join(",") %></td></tr>
      </tbody>
    </table>

  </div> <!-- summary -->
  
  <br>
  <div id="years">

    <table id="player-teams">
      <thead>
        <tr>
          <% 16.times do %> <col> <% end %>
          <th>Year</td>
          <th>Team</td>
          <th>P2</td>
          <th>D#</td>
          <th>R1</td>
          <th>R2</td>
          <th>R3</td>
          <th>R4</td>
          <th>R5</td>
          <th>R6</td>
          <th>RT</td>
          <th>PT</td>
          <th>HI</th>
          <th>#1</th>
          <th>#S</th>
          <th>LO</th>
          <th align="right">$$</td>
        </tr>
      </thead>
      <tbody>
        <% @player.teams.each_with_index do |team, index| %>

          <tr>
          <td><%= link_to team.year, teams_path(anchor:team.year) %>   </td>
          <td class="align-left"><%= team.name %>   </td>
          <td class="align-left">
            <% if team.partner(@player) %>
              <%= link_to team.partner(@player).short_name, player_path(team.partner(@player)) %>
            <% end %>
          </td>
          <td><%= team.draft %>  </td>
          <td><%= team.r1 %>  </td>
          <td><%= team.r2 %>  </td>
          <td><%= team.r3 %>  </td>
          <td><%= team.r4 %>  </td>
          <td><%= team.r5 %>  </td>
          <td><%= team.r6 %>  </td>
          <td><%= team.wins %>  </td>
          <td><%= team.pts %>  </td>
          <td><%= team.ptschamp ? image_tag("ptscrown_sm.png", width:"10px"): "" %></td>
          <td><%= team.r6 == 1 ?  image_tag("crown_sm.png", width:"10px"): "" %></td>
          <td><%= team.low ? image_tag("acorn_sm.png", width:"10px"): ""%></td>
          <td><%= team.goat ? image_tag("goat_sm.png", width:"10px"): "" %></td>
          <td class="align-right"><%= number_to_currency(team.player_earnings) %></td>
          </tr>
        <% end%>
      </tbody>
    </table>
    <br>
  </div> <!-- body -->